app:
  title: "Default 1234"
  message: "default message 1234"
  features:
    maxDays: 1

service1:
  name: "default 1234"
  useAdvancedAlgorithm: false
AdminSettings:
  ApplicationTitle: "ABCD123456789"
DefaultCounts:
  SuggestedSearchCount: 50000
AdminSettings:
  DomainDisplay: "https://localhost:5011/"
